import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class TaskScreen extends StatefulWidget {
  const TaskScreen({ Key? key }) : super(key: key);

  @override
  _TaskScreenState createState() => _TaskScreenState();
}

class _TaskScreenState extends State<TaskScreen> {
  
  @override
  Widget build(BuildContext context) {
    var t = AppLocalizations.of(context);
    return Scaffold(
      // appBar: AppBar(
      //   backgroundColor: Color(0xFF2e2f43),
      //   title: Text(t!.appBarTitle), // Using the translation generated by the AppLocalization class imported on top of this script
      // ),
      body: Container(
          child: Center(
            child: Text('Hello world'),
          ),
        ),
    );
  }
}